In [1]:
import pandas as pd

pd.__version__

'3.0.5'

In [7]:
score = [['홍길동',100,90,80],
          ['정약용',80,90,100],
          ['고양이',10,20,30]]

score_df = pd.DataFrame(score, columns=['이름','국어','영어','수학'])

score_df

    이름   국어  영어   수학
0  홍길동  100  90   80
1  정약용   80  90  100
2  고양이   10  20   30

In [5]:
score_df.drop([0])

Empty DataFrame
Columns: [이름, 국어, 영어, 수학]
Index: []

In [6]:
score_df.drop(['국어'], axis=1)

    이름  영어  수학
0  홍길동  90  80

In [8]:
score_df.drop([1], inplace=True)
score_df

    이름   국어  영어  수학
0  홍길동  100  90  80
2  고양이   10  20  30

In [10]:
score_df.reset_index(drop=True)

    이름   국어  영어  수학
0  홍길동  100  90  80
1  고양이   10  20  30